version: "3.8"
services:
  airflow-webserver:
    image: apache/airflow:2.9.3
    environment:
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
    volumes:
      - ../../dags:/opt/airflow/dags
      - ../../pipelines:/opt/airflow/pipelines
    ports:
      - "8080:8080"
