from airflow.decorators import dag, task
from datetime import datetime, timedelta
import os
import tempfile

from google.cloud import storage
from google.oauth2 import service_account

default_args = {
    "retries": 3,
    "retry_delay": timedelta(minutes=5),
}

# Path to your service account file (same idea as your Cloud Run DAG)
SERVICE_ACCOUNT_FILE = "/opt/airflow/credgcp.json"

# Buckets
SOURCE_BUCKET = "os-dpf-ariflow-prj-dev"
DESTINATION_BUCKET = "os-dpf-ariflow-prj-shr-dev"

# Object paths
SOURCE_OBJECT = "n8n/sample_upload.txt"
DESTINATION_OBJECT = "Archive/sample_upload.txt"


def get_gcs_client():
    credentials = service_account.Credentials.from_service_account_file(
        SERVICE_ACCOUNT_FILE
    )
    return storage.Client(credentials=credentials)


@dag(
    dag_id="gcs_upload_move_delete_with_sa",
    start_date=datetime(2026, 2, 2),
    schedule=None,
    catchup=False,
    default_args=default_args,
    tags=["gcs", "service-account", "upload", "move", "delete"],
)
def gcs_upload_move_delete_with_sa():

    @task()
    def create_local_file() -> str:
        temp_dir = tempfile.gettempdir()
        file_path = os.path.join(temp_dir, "sample_upload.txt")

        with open(file_path, "w", encoding="utf-8") as f:
            f.write("Test file generated by Airflow using service account.\n")

        return file_path

    @task()
    def upload_to_gcs(file_path: str) -> str:
        client = get_gcs_client()
        bucket = client.bucket(SOURCE_BUCKET)
        blob = bucket.blob(SOURCE_OBJECT)

        blob.upload_from_filename(file_path)

        return SOURCE_OBJECT

    @task()
    def move_between_buckets(source_object: str) -> str:
        client = get_gcs_client()

        source_bucket = client.bucket(SOURCE_BUCKET)
        destination_bucket = client.bucket(DESTINATION_BUCKET)

        source_blob = source_bucket.blob(source_object)

        # Copy to destination
        destination_blob = source_bucket.copy_blob(
            source_blob,
            destination_bucket,
            DESTINATION_OBJECT
        )

        # Delete from source (completes "move")
        source_blob.delete()

        return DESTINATION_OBJECT

    @task()
    def delete_from_destination(destination_object: str) -> str:
        client = get_gcs_client()

        bucket = client.bucket(DESTINATION_BUCKET)
        blob = bucket.blob(destination_object)

        blob.delete()

        return f"Deleted gs://{DESTINATION_BUCKET}/{destination_object}"

    file_path = create_local_file()
    uploaded = upload_to_gcs(file_path)
    moved = move_between_buckets(uploaded)
    delete_from_destination(moved)


gcs_upload_move_delete_with_sa()